export const capabilities = {
  circuit: {
    CREATE_CIRCUIT: "CREATE_CIRCUIT",
    EDIT_CIRCUIT: "EDIT_CIRCUIT",
    DELETE_CIRCUIT: "DELETE_CIRCUIT",
  },
  component: {
    CREATE_COMPONENT: "CREATE_COMPONENT",
    READ_COMPONENT: "READ_COMPONENT",
    UPDATE_COMPONENT: "UPDATE_COMPONENT",
    DELETE_COMPONENT: "DELETE_COMPONENT",
    HIGHLIGHT_COMPONENT: "HIGHLIGHT_COMPONENT",
  },
  wiring: {
    CREATE_WIRE: "CREATE_WIRE",
    DELETE_WIRE: "DELETE_WIRE",
    UPDATE_WIRE: "UPDATE_WIRE",
  },
  analysis: {
    RUN_DRC: "RUN_DRC",
    CALCULATE_POWER_CONSUMPTION: "CALCULATE_POWER_CONSUMPTION",
    CALCULATE_LED_RESISTOR: "CALCULATE_LED_RESISTOR",
  },
  knowledge: {
    ASK_KNOWLEDGE_BASE: "ASK_KNOWLEDGE_BASE",
    EXPLAIN_COMPONENT: "EXPLAIN_COMPONENT",
    EXPLAIN_CIRCUIT: "EXPLAIN_CIRCUIT",
  },
  scaffolding: {
    SCAFFOLD_CIRCUIT: "SCAFFOLD_CIRCUIT",
  },
  review: {
    REVIEW_CIRCUIT: "REVIEW_CIRCUIT",
    SUGGEST_OPTIMIZATIONS: "SUGGEST_OPTIMIZATIONS",
  },
  netlist: {
    GENERATE_NETLIST: "GENERATE_NETLIST",
    GENERATE_BOM: "GENERATE_BOM",
    PREPARE_FOR_MANUFACTURING: "PREPARE_FOR_MANUFACTURING",
  },
  project: {
    ZOOM_IN: "ZOOM_IN",
    ZOOM_OUT: "ZOOM_OUT",
    PAN_CANVAS: "PAN_CANVAS",
    SAVE_PROJECT: "SAVE_PROJECT",
    GROUP_COMPONENTS: "GROUP_COMPONENTS",
  },
} as const;

export type Capability =
  (typeof capabilities)[keyof typeof capabilities][keyof (typeof capabilities)[keyof typeof capabilities]];
